name: Build, Push and Deploy Dispatch Auto

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/support_bot:latest

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🔁 Pulling latest Docker image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/support_bot:latest

            echo "🛑 Stopping old container (if exists)..."
            docker stop support_bot || true
            docker rm support_bot || true

            echo "🚀 Starting new container..."
            cd /srv/deploy_config
            docker compose up -d
